CREATE TABLE USERS(
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_USERID VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(30) NOT NULL,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    PHONE_NUMBER VARCHAR(30),
    EMAIL VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(60),
    START_DATE DATE,
    CARD_INFO VARCHAR(20)
);

CREATE TABLE PRODUCT(
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    PRODUCT_TYPE VARCHAR(50) NOT NULL,
    PRODUCT_PRICE FLOAT NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(1000)
);
CREATE TABLE USERORDER(
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    ORDER_DATE DATE
);

ALTER TABLE USERORDER ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE USERORDER ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
CREATE INDEX IDX_START_DATE_ ON USERS(START_DATE);
CREATE INDEX IDX_ORDER_DATE_ ON USERORDER(ORDER_DATE);